version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: courses_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursera-app-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/courses_app
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 12345